version: '3.8'

services:
  gradio-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=8080
      - GROQ_API_KEY=${GROQ_API_KEY}
